# Generated by Django 4.1.3 on 2022-11-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=50, verbose_name='Přijmení')),
                ('narozeni', models.DateField(verbose_name='Datum narození')),
                ('uz_jmene', models.CharField(max_length=30, verbose_name='uzivatelske jmeno')),
                ('heslo', models.CharField(max_length=100, verbose_name='heslo')),
            ],
            options={
                'verbose_name_plural': 'Registrace',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
    ]
