# Generated by Django 4.1.3 on 2022-11-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slipka_gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trenink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis', models.CharField(max_length=300, verbose_name='popis_tréninku')),
                ('datum', models.DateField(verbose_name='datum_konani_treninku')),
                ('cas', models.TimeField(verbose_name='cas_konani_treninku')),
                ('misto', models.CharField(max_length=20, verbose_name='misto_konani_treninku')),
            ],
            options={
                'verbose_name_plural': 'Trénink',
                'ordering': ['datum', 'cas'],
            },
        ),
    ]
