# Generated by Django 4.0.4 on 2022-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slipka_gym', '0002_trenink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trenink',
            name='misto',
            field=models.CharField(choices=[('venku', 'Venku'), ('mala_telocvicna', 'Malá tělovična'), ('velka_telecvicna', 'Velká tělocvična')], max_length=20, verbose_name='misto_konani_treninku'),
        ),
    ]
